In [2]:
import numpy as np

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [55]:
N = int(input('Введите длину массива:'))
mas = np.arange(0, N)
mas[::-1]

Введите длину массива:95


array([94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78,
       77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61,
       60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44,
       43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27,
       26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,
        9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [58]:
for i in range(2,6):
    if N % i == 0:
        n = int(N / i)
        a = mas[::-1].reshape(n,i)
        print(a)
        print(np.sum(np.diag(a)))

[[94 93 92 91 90]
 [89 88 87 86 85]
 [84 83 82 81 80]
 [79 78 77 76 75]
 [74 73 72 71 70]
 [69 68 67 66 65]
 [64 63 62 61 60]
 [59 58 57 56 55]
 [54 53 52 51 50]
 [49 48 47 46 45]
 [44 43 42 41 40]
 [39 38 37 36 35]
 [34 33 32 31 30]
 [29 28 27 26 25]
 [24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
410


## Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [79]:
a = np.array( [[4, 2, 1],[4, 3, 0],[0, 5, 4]])
b = np.array( [12, 12, -3])

In [80]:
from numpy import linalg

In [81]:
linalg.solve(a, b)

array([ 3.25      , -0.33333333, -0.33333333])

## Задача 4 домашнего задания

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array
In [ ]:


users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)




На сайт заходит очередной посетитель, о покупках которого известно следующее:
In [ ]:


next_user_stats = np.array([0, 1, 2, 0, 0, 0])




Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [26]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [50]:
def cosine( a, b ):    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )
user_id = 1
max_cos = float(180)
for i in users_stats:
    a = next_user_stats
    b = i
    c = np.arccos( cosine( a, b ) ) * 360 / 2 / np.pi
    if max_cos > c:
        max_cos = c
        max_user_id = user_id
    user_id +=1
print("Самы похожий пользователь имеет ID:", max_user_id, "Угол между векторами =", int(max_cos))

Самы похожий пользователь имеет ID: 8 Угол между векторами = 18
